
package ug.or.nda.wsp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "paymentWebService", targetNamespace = "http://wsp.nda.or.ug", wsdlLocation = "http://localhost:8080/ndamisws/invoice/payment/v1.0?wsdl")
public class PaymentWebService_Service
    extends Service
{

    private final static URL PAYMENTWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ug.or.nda.wsp.PaymentWebService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ug.or.nda.wsp.PaymentWebService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ndamisws/invoice/payment/v1.0?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ndamisws/invoice/payment/v1.0?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAYMENTWEBSERVICE_WSDL_LOCATION = url;
    }

    public PaymentWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentWebService_Service() {
        super(PAYMENTWEBSERVICE_WSDL_LOCATION, new QName("http://wsp.nda.or.ug", "paymentWebService"));
    }

    /**
     * 
     * @return
     *     returns PaymentWebService
     */
    @WebEndpoint(name = "paymentWebServicePort")
    public PaymentWebService getPaymentWebServicePort() {
        return super.getPort(new QName("http://wsp.nda.or.ug", "paymentWebServicePort"), PaymentWebService.class);
    }

}
