
package ug.or.nda.wsp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ug.or.nda.ws.PaymentNotificationRequest;
import ug.or.nda.ws.PaymentNotificationResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "paymentWebService", targetNamespace = "http://wsp.nda.or.ug")
public interface PaymentWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ug.or.nda.ws.PaymentNotificationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "paymentNotification", targetNamespace = "http://wsp.nda.or.ug", className = "ug.or.nda.wsp.PaymentNotification")
    @ResponseWrapper(localName = "paymentNotificationResponse", targetNamespace = "http://wsp.nda.or.ug", className = "ug.or.nda.wsp.PaymentNotificationResponse")
    public PaymentNotificationResponse paymentNotification(
        @WebParam(name = "arg0", targetNamespace = "")
        PaymentNotificationRequest arg0);

}
