
package ug.or.nda.wsi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "invoiceWebService", targetNamespace = "http://wsi.nda.or.ug", wsdlLocation = "http://212.22.169.19/ndamisws/invoice/validation/v1.0?wsdl")
public class InvoiceWebService
    extends Service
{

    private final static URL INVOICEWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ug.or.nda.wsi.InvoiceWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ug.or.nda.wsi.InvoiceWebService.class.getResource(".");
            url = new URL(baseUrl, "http://212.22.169.19/ndamisws/invoice/validation/v1.0?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://212.22.169.19/ndamisws/invoice/validation/v1.0?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INVOICEWEBSERVICE_WSDL_LOCATION = url;
    }

    public InvoiceWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InvoiceWebService() {
        super(INVOICEWEBSERVICE_WSDL_LOCATION, new QName("http://wsi.nda.or.ug", "invoiceWebService"));
    }

    /**
     * 
     * @return
     *     returns ValidationWebService
     */
    @WebEndpoint(name = "validationWebServicePort")
    public ValidationWebService getValidationWebServicePort() {
        return super.getPort(new QName("http://wsi.nda.or.ug", "validationWebServicePort"), ValidationWebService.class);
    }

}
