
package ug.or.nda.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ug.or.nda.service.InvoiceValidationRequest;
import ug.or.nda.service.InvoiceValidationResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "invoiceservice", targetNamespace = "http://services.nda.or.ug")
public interface Invoiceservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns ug.or.nda.service.InvoiceValidationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateInvoice", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.ValidateInvoice")
    @ResponseWrapper(localName = "validateInvoiceResponse", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.ValidateInvoiceResponse")
    public InvoiceValidationResponse validateInvoice(
        @WebParam(name = "arg0", targetNamespace = "")
        InvoiceValidationRequest arg0);

}
