
package ug.or.nda.services;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "InvoiceServiceService", targetNamespace = "http://services.nda.or.ug", wsdlLocation = "http://localhost:8080/broker/paymentService?wsdl")
public class InvoiceServiceService
    extends Service
{

    private final static URL INVOICESERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ug.or.nda.services.InvoiceServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ug.or.nda.services.InvoiceServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/broker/paymentService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/broker/paymentService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INVOICESERVICESERVICE_WSDL_LOCATION = url;
    }

    public InvoiceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InvoiceServiceService() {
        super(INVOICESERVICESERVICE_WSDL_LOCATION, new QName("http://services.nda.or.ug", "InvoiceServiceService"));
    }

    /**
     * 
     * @return
     *     returns Invoiceservice
     */
    @WebEndpoint(name = "invoiceservicePort")
    public Invoiceservice getInvoiceservicePort() {
        return super.getPort(new QName("http://services.nda.or.ug", "invoiceservicePort"), Invoiceservice.class);
    }

}
