
package ug.or.nda.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ug.or.nda.service.PaymentNotificationRequest;
import ug.or.nda.service.PaymentNotificationResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "paymentService", targetNamespace = "http://services.nda.or.ug")
public interface PaymentService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ug.or.nda.service.PaymentNotificationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "paymentNotification", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.PaymentNotification")
    @ResponseWrapper(localName = "paymentNotificationResponse", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.PaymentNotificationResponse")
    public PaymentNotificationResponse paymentNotification(
        @WebParam(name = "arg0", targetNamespace = "")
        PaymentNotificationRequest arg0);

}
